Repository AleksandrKoltsov/camp_site, pull requests merged in 2020-05, with the labels that each got.

#2 Release to production
  README.txt
Labels: release

#5 worked validator, 3 fields - name, phone, email
  package-lock.json
  package.json
  src/components/Forms.js
  src/components/FullCard.js
  src/components/Validator.js
Labels: release

#8 patch datapicker v 0.1
  package-lock.json
  package.json
  src/components/DatePicker.js
  src/components/Forms.js
  src/components/FullCard.js
Labels: wontfix

#17 Patch/svgmap
  src/App.js
  src/components/AdvancedGridList.js
  src/components/DatePicker.js
  src/components/SliderCards.js
  src/components/TerritoryMap.js
  src/components/territoryMapComponents/HouseMap.js
Labels: patch
