Repository AleksandrKoltsov/camp_site, pull requests merged in 2020-06, with the labels that each got.

#29 Aleks
  package.json
  src/App.js
  src/components/Fitback/Fitback.js
  src/components/Fitback/Review.js
  src/components/Forms.js
  src/components/Validator.js
Labels: patch

#32 Daniil/patch/grid-cards
  src/App.js
  src/components/SliderCards.js
Labels: patch

#35 Change load methods
  src/App.js
  src/components/SliderCards.js
Labels: patch

#39 Some fixes from Daniil
  src/App.js
  src/components/Fitback/Fitback.js
  src/components/SliderCards.js
Labels: patch

#44 Fix bug with cards slider (one swipe change state for all sliders)
  src/components/Fitback/Review.js
  src/components/Logo.js
  src/components/MainPage.js
  src/components/Scroll.js
  src/components/Slider.js
  src/components/SliderCards.js
  src/components/TerritoryMap.js
  src/components/fullCardComponent/Modal.js
  src/components/fullCardComponent/Slider.js
  src/components/territoryMapComponents/HouseMap.js
  src/components/territoryMapComponents/RoadMap.js
  src/components/territoryMapComponents/TextMap.js
Labels: bug

#47 Patch message
  src/App.js
  src/components/Feedback/Feedback.js
  src/components/MainPage.js
  src/components/Message.js
Labels: patch

#48 Aleks
  src/App.js
  src/components/Feedback/Feedback.js
  src/components/Feedback/Review.js
  src/components/Forms.js
  src/components/FullCard.js
  src/components/MainPage.js
  src/components/Message.js
  src/components/fullCardComponent/Slider.js
Labels: patch

#50 Patch/google map
  package-lock.json
  package.json
  src/App.js
  src/components/Map.js
Labels: patch

#52 Daniil/patch/google-maps
  package-lock.json
  package.json
  src/App.js
  src/components/Map.js
Labels: patch

#58 Patch footer
  src/App.js
  src/components/Footer.js
  src/components/Forms.js
  src/components/MainPage.js
Labels: patch

#59 Aleks
  src/App.js
  src/components/Footer.js
  src/components/Forms.js
  src/components/MainPage.js
Labels: patch

#64 fixed bug FullCard
  src/components/FullCard.js
Labels: patch

#66 fix invalid width on message
  src/components/Message.js
Labels: invalid

#67 Patch/adaptive cards
  src/App.js
  src/components/AdvancedGridList.js
  src/components/MainPage.js
Labels: patch

#68 Merge branch Daniil to develop
  package-lock.json
  src/App.js
  src/components/AdvancedGridList.js
  src/components/MainPage.js
Labels: patch

#71 Bugfix form
  src/components/Forms.js
  src/components/Message.js
Labels: bug

#74 Patch news
  src/App.js
  src/components/News/News.js
  src/components/News/Post.js
Labels: patch

#75 Aleks
  src/App.js
  src/components/AboutUs.js
  src/components/Feedback/Feedback.js
  src/components/Footer.js
  src/components/News/News.js
  src/components/News/Post.js
  tatus
Labels: patch

#91 Fix layout bugs
  src/App.js
  src/components/Footer.js
Labels: patch

#92 Some bug fixes
  src/App.js
  src/components/Feedback/Feedback.js
  src/components/Forms.js
  src/components/Slider.js
Labels: patch

#93 Daniil
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/site.webmanifest
Labels: patch

#94 add num house
  src/App.js
  src/components/Forms.js
Labels: invalid
